#!/usr/bin/env python #-*- coding:utf-8 -*- import os
import random
import sys
from subprocess import Popen,PIPE
import sqlite3
import json
import time
import web

DEBUG = True
db = "/home/zjf/swfit_demo_db/9/b9/f5d1278e8109edd94e1e4197e04873b9.db"
tableName = "nodetree"

    #c.execute("""
    #CREATE TABLE `nodetree` (
        #`id` INTEGER PRIMARY KEY NOT NULL,
        #`name` VARCHAR(75) NOT NULL,
        #`fId` INTEGER NOT NULL,
        #`type` INTEGER NOT NULL,
        #`atime` TIMESTAMP DEFAULT (datetime('now', 'localtime')) NOT NULL,
        #`attr` VARCHAR(75)
         #);
    #""")
conn=sqlite3.connect(db)
conn.text_factory=str


def getChildNode(nodeId, nodeType, conn):
    """接受一个nodeId, 和该节点的类型。 返回它的子节点的Id和类型。 """
    if nodeType == 1:
        return []
    elif nodeType == 0:
        c=conn.cursor()
        txt=c.execute("select * from '%s' where fId = '%s' "%(tableName, nodeId))
        childNode = []
        for row in txt:
            print "row:%s"%str(row), row[0]
            childNode.append({"id":row[0], "name":row[1], 'fid':row[2], 
                "type":row[3], 'atime':row[4], 'attr':row[5]})
        c.close
        return childNode
    else:
        raise Exception('i do not understander your type:%s'%(nodeType))

def getJson(fnode, conn):
    """在构建每个节点的id时候，是其父节点和节点的id的组合，为了方便上层的删除操作。
        nodeId为整数，nodeType 为group, user.
        使用递归的方式
    """
    c=conn.cursor()
    if fnode['type'] == 1:
        return None
    elif fnode['type'] == 0:
        txt=c.execute("select * from '%s' where id='%s' and type=0"%(tableName, fId))
        print txt, tableName, fId
        nodeJson = {}
        for row in txt:
            nodeJson = {"data":row[0], "attr":{"id":"node_"+str(row[0])+"_"+str(nodeId)+"_"+str(nodeType), "rel":row[3]}, "children":[],"state":"open"} 
        childNode = getChildNode(nodeId, nodeType, conn)
        if childNode == []:
            return nodeJson
        else:
            for node in childNode:
                childNodeJson = {"data":node['id'], "attr":{"id": "node_"+str(node['id'])+"_"+str(nodeId)+"_"+str(nodeType), "rel":node['type']},}
                nodeJson["children"].append(childNodeJson)
            return nodeJson

if __name__=="__main__":
    nodes  = getChildNode(-1, 0, conn)
    for node in nodes:
        print getJson(node['id'], node['type'], conn)
